### ISSUE TITLE
Add some badges to the README

### ISSUE THREAD

**Issue by Umesh-01** [bansalkanav/Machine_Learning_and_Deep_Learning#5]
### Description
Add some badges to the top of readme.md file, since the badges will be colorful and more attractive at the top of README.md file than the text the users will like it and after linking the badges it will also help them to navigate to different sections/ webpages like PRs, issues, contributors, etc.

### Solution
I will add some badges at the top and also will add links related to them so that the README.md file will look more interactive and awesome.

**Comment by Umesh-01** [comment]
@bansalkanav should I work on this issue??

**Comment by bansalkanav** [comment]
Replying a little late. Apologies for that. 

Sure, you can work on it. I will be monitoring the pull requests.
